version: "3.2"

services:

  nginx:
    image: nginx:latest
    container_name: nginxBalancerServer
    volumes:
      - /home/esgodra/compose/nginx_tomcat_balancer/nginx.conf:/etc/nginx/nginx.conf
    networks:
      gateway-net:
        ipv4_address: 10.10.1.10

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: poke_admin
      MYSQL_DATABASE: pokemon_go
      MYSQL_USER: poke_user
      MYSQL_PASSWORD: poke_pass
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      gateway-net:
        ipv4_address: 10.10.1.13

  tomcat_server01:
    image: tomcat
    container_name: tomcat_server01
    volumes:
      - /home/esgodra/compose/tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      gateway-net:
        ipv4_address: 10.10.1.11
    links:
      - db

  tomcat_server02:
    image: tomcat
    container_name: tomcat_server02
    volumes:
      - /home/esgodra/compose/tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      gateway-net:
        ipv4_address: 10.10.1.12
    links:
      - db

networks:
 gateway-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.10.1.0/27
